#pragma config(Motor,  port2,           left,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           right,         tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port4,           left2,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           right2,        tmotorServoStandard, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
    while(true)  // Run the loop indefinitely to check joystick input
    {
        // Get joystick values for the left and right joysticks
        int leftJoystick = vexRT[Ch3];  // Left vertical joystick (Ch3)
        int rightJoystick = vexRT[Ch2]; // Right vertical joystick (Ch2)

        // Map the joystick value range (-127 to 127) to motor speed range (-127 to 127)
        // The joystick values typically range from -127 to 127 (full range)
        // The motor speed range is also -127 to 127 (full speed forward to full speed reverse)

        motor[left] = leftJoystick;
        motor[left2] = leftJoystick;

        motor[right] = rightJoystick;
        motor[right2] = rightJoystick;

        // Small delay to allow the system to update motor speeds
        wait1Msec(20);
    }
}
