#pragma config(Motor,  port2,           right_stacker1, tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,           right_stacker2, tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           tread1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           tread2,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           left_stacker2, tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           left_stacker1, tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
    while(true)  // Run the loop indefinitely to check joystick input
    {

        // Map the joystick value range (-127 to 127) to motor speed range (-127 to 127)
        // The joystick values typically range from -127 to 127 (full range)
        // The motor speed range is also -127 to 127 (full speed forward to full speed reverse)
				//theses are the tread motors on the left
    		motor[tread1] = 127;
				motor[tread2] = 127;
				motor[left_stacker1] = 127;
				motor[left_stacker2] = 127;
				motor[right_stacker2] = -127;
				motor[right_stacker1] = -127;

        // Small delay to allow the system to update motor speeds
        wait1Msec(20);
    }
}
